# NOTE: To build this you will need a docker version >= 19.03 and DOCKER_BUILDKIT=1
#
#       If you do not use buildkit you are not going to have a good time
#
#       For reference:
#           https://docs.docker.com/develop/develop-images/build_enhancements/

ARG UBUNTU_VERSION=20.04

FROM ubuntu:${UBUNTU_VERSION} as base

# See http://bugs.python.org/issue19846
ENV LANG C.UTF-8
ARG PYTHON=python3

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends --fix-missing \
    ${PYTHON} \
    ${PYTHON}-pip

RUN ${PYTHON} -m pip --no-cache-dir install --upgrade \
    pip \
    setuptools \
    psutil

# Some TF tools expect a "python" binary
RUN ln -s $(which ${PYTHON}) /usr/local/bin/python

ARG PYTORCH_VERSION=2.0.1
ARG TIKTOKEN_VERSION=0.4.0
ARG GRADIO_VERSION=3.36.1
ARG TORCH_CPU_URL=https://download.pytorch.org/whl/cpu/torch_stable.html

RUN \
    python -m pip install --no-cache-dir \
    torch==${PYTORCH_VERSION}+cpu -f ${TORCH_CPU_URL} tiktoken==${TIKTOKEN_VERSION} gradio==${GRADIO_VERSION}

WORKDIR /workspace

COPY ["app-gpt.py", "model_gpt.trace.pt" , "."]

EXPOSE 8080

CMD [ "python3" , "app-gpt.py" ]