# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - model: gpt.yaml
  - callbacks: null
  - logger: null
  - paths: default.yaml
  - trainer: null
  - experiment: null
  - hydra: default.yaml
  - hparams_search: null

# task name, determines output directory path
task_name: "convert"

# checkpoint is necessary for conversion
ckpt_path: ???