# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: cifar10.yaml
  - model: timm.yaml
  - paths: default.yaml
  - trainer: default.yaml
  - experiment: null

# task name, determines output directory path
task_name: "infer"

# compile model for faster training with pytorch 2.0
compile: False

# passing checkpoint path is necessary for evaluation
ckpt_path: ???

# passing image path is necessary for inference
img_path: ???

# value of 'k' for top-k predictions
topk: 2

# seed for random number generators in pytorch, numpy and python.random
seed: 42 