# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: cifar10.yaml
  - model: timm.yaml
  - callbacks: default.yaml
  - logger: null
  - paths: default.yaml
  - trainer: default.yaml
  - experiment: null
  - hydra: default.yaml
  - hparams_search: null

# task name, determines output directory path
task_name: "train"

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

# compile model for faster training with pytorch 2.0
compile: True

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: 42